export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const GET_PROJECTS_LIST_START = 'GET_PROJECTS_LIST_START'
export const GET_PROJECTS_LIST_SUCCESS = 'GET_PROJECTS_LIST_SUCCESS'
export const GET_PROJECTS_LIST_FAIL = 'GET_PROJECTS_LIST_FAIL'

export const CREATE_PROJECT_START = 'CREATE_PROJECT_START'
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS'
export const CREATE_PROJECT_FAIL = 'CREATE_PROJECT_FAIL'

