# Generated by Django 2.2.7 on 2020-05-05 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectbuilder', '0002_auto_20200503_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklytask',
            name='bug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='projectbuilder.Bug'),
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projectbuilder.Project'),
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='todo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='todo', to='projectbuilder.Todo'),
        ),
    ]
