# Generated by Django 2.2.7 on 2020-05-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectbuilder', '0003_auto_20200505_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklytask',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
